[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python3 -m ensurepip --upgrade",
  "python3 -m pip install --upgrade pip",
  "pip install -r server/requirements.txt"
]

[start]
cmd = "python server/server.py"
